name: Bun CI

on:
  push:
    branches: [main]
    paths: [backend/bun/**, .github/workflows/bun.yaml]
  pull_request:
    branches: [main]
    paths: [backend/bun/**, .github/workflows/bun.yaml]

jobs:
  backend-bun:
    name: Backend Bun
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/bun
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun build index.ts --outfile /tmp/bun-backend.js
