name: Deno CI

on:
  push:
    branches: [main]
    paths: [backend/deno/**, .github/workflows/deno.yaml]
  pull_request:
    branches: [main]
    paths: [backend/deno/**, .github/workflows/deno.yaml]

jobs:
  backend-deno:
    name: Backend Deno
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/deno
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno check main.ts
