name: Dotnet CI

on:
  push:
    branches: [main]
    paths: [backend/dotnet/**, .github/workflows/dotnet.yaml]
  pull_request:
    branches: [main]
    paths: [backend/dotnet/**, .github/workflows/dotnet.yaml]

jobs:
  backend-dotnet:
    name: Backend .NET
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/dotnet
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore SumUpExamples.csproj

      - name: Format
        run: dotnet format SumUpExamples.csproj --verify-no-changes

      - name: Build
        run: dotnet build SumUpExamples.csproj --configuration Release --no-restore
