name: Static CI

on:
  push:
    branches: [main]
    paths: [frontend/static/**, .github/workflows/static.yaml]
  pull_request:
    branches: [main]
    paths: [frontend/static/**, .github/workflows/static.yaml]

jobs:
  frontend-static:
    name: Frontend Static
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/static
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '20'

      - name: Check JavaScript syntax
        run: node --check app.js

      - name: Lint (Prettier)
        run: npx --yes prettier --check "**/*.{js,css,html}"
